// this file is auto-generated, please do not edit this file。
// 该文件是自动生成的文件，请不要编辑。
//
package com.azalea.cafe.cafe

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.staticCompositionLocalOf
import kotlin.Unit
import kotlinx.coroutines.flow.MutableStateFlow

public object Cafe {
  public val color: CafeColor
    @Composable
    get() = CafeProvider.colorProvider.current

  public val mipmap: CafeMipmap
    @Composable
    get() = CafeProvider.mipmapProvider.current

  public val drawable: CafeDrawable
    @Composable
    get() = CafeProvider.drawableProvider.current

  public fun setCup(cup: Cup) {
    CafeProvider.cupFlow.tryEmit(cup)
  }

  public fun getCup(): Cup = CafeProvider.cupFlow.value
}

public object CafeProvider {
  public val colorProvider: ProvidableCompositionLocal<CafeColor> =
      staticCompositionLocalOf<CafeColor> { error("null") }


  public val mipmapProvider: ProvidableCompositionLocal<CafeMipmap> =
      staticCompositionLocalOf<CafeMipmap> { error("null") }


  public val drawableProvider: ProvidableCompositionLocal<CafeDrawable> =
      staticCompositionLocalOf<CafeDrawable> { error("null") }


  public val cupFlow: MutableStateFlow<Cup> = MutableStateFlow(MAIN)

}

@Composable
public fun CafeTheme(content: @Composable () -> Unit) {
  val cup by CafeProvider.cupFlow.collectAsState()

      CompositionLocalProvider(
          CafeProvider.colorProvider provides cup.color,
      CafeProvider.mipmapProvider provides cup.mipmap,
      CafeProvider.drawableProvider provides cup.drawable,

      ) {
          content()
      }
}
