// this file is auto-generated, please do not edit this file。
// 该文件是自动生成的文件，请不要编辑。
//
package com.azalea.cafe.cafe

import androidx.`annotation`.ColorRes
import androidx.`annotation`.DrawableRes
import kotlin.Int

public class CafeColor {
  @ColorRes
  public var purple_500: Int = com.azalea.cafe.R.color.purple_500

  @ColorRes
  public var purple_700: Int = com.azalea.cafe.R.color.purple_700

  @ColorRes
  public var teal_200: Int = com.azalea.cafe.R.color.teal_200

  @ColorRes
  public var teal_700: Int = com.azalea.cafe.R.color.teal_700

  @ColorRes
  public var black: Int = com.azalea.cafe.R.color.black

  @ColorRes
  public var white: Int = com.azalea.cafe.R.color.white

  @ColorRes
  public var purple_200: Int = com.azalea.cafe.R.color.purple_200
}

public class CafeMipmap {
  @DrawableRes
  public var sky: Int = com.azalea.cafe.R.mipmap.sky

  @DrawableRes
  public var ic_launcher: Int = com.azalea.cafe.R.mipmap.ic_launcher

  @DrawableRes
  public var ic_launcher_round: Int = com.azalea.cafe.R.mipmap.ic_launcher_round
}

public class CafeDrawable {
  @DrawableRes
  public var ic_launcher_background: Int = com.azalea.cafe.R.drawable.ic_launcher_background

  @DrawableRes
  public var ic_launcher_foreground: Int = com.azalea.cafe.R.drawable.ic_launcher_foreground

  @DrawableRes
  public var sky: Int = com.azalea.cafe.R.drawable.sky
}
