// this file is auto-generated, please do not edit this file。
// 该文件是自动生成的文件，请不要编辑。
//
package cn.loopon.cafe

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.staticCompositionLocalOf
import kotlin.Unit
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow

public object Cafe {
  public val mipmap: ProvidableCompositionLocal<CafeMipmap> = staticCompositionLocalOf<CafeMipmap> {
      error("null") }


  public val drawable: ProvidableCompositionLocal<CafeDrawable> =
      staticCompositionLocalOf<CafeDrawable> { error("null") }


  public val color: ProvidableCompositionLocal<CafeColor> = staticCompositionLocalOf<CafeColor> {
      error("null") }


  public val _themeFlow: MutableStateFlow<Cup> = MutableStateFlow<Cup>(MAIN)


  public fun setTheme(theme: Cup) {
    _themeFlow.tryEmit(theme)
  }

  public fun getTheme(): StateFlow<Cup> = _themeFlow
}

@Composable
public fun CafeTheme(content: @Composable () -> Unit) {
  val theme by Cafe.getTheme().collectAsState()

      CompositionLocalProvider(
          Cafe.mipmap provides theme.mipmap,
      Cafe.drawable provides theme.drawable,
      Cafe.color provides theme.color,

      ) {
          content()
      }
}
