// this file is auto-generated, please do not edit this file。
// 该文件是自动生成的文件，请不要编辑。
//
package cn.loopon.cafe

import androidx.`annotation`.ColorRes
import androidx.`annotation`.DrawableRes
import kotlin.Int

public data class CafeColor(
  @ColorRes
  public val purple_200: Int,
  @ColorRes
  public val purple_500: Int,
  @ColorRes
  public val purple_700: Int,
  @ColorRes
  public val teal_200: Int,
  @ColorRes
  public val teal_700: Int,
  @ColorRes
  public val black: Int,
  @ColorRes
  public val white: Int,
)

public data class CafeMipmap(
  @DrawableRes
  public val sky: Int,
  @DrawableRes
  public val ic_launcher: Int,
  @DrawableRes
  public val ic_launcher_round: Int,
)

public data class CafeDrawable(
  @DrawableRes
  public val ic_launcher_background: Int,
  @DrawableRes
  public val ic_launcher_foreground: Int,
  @DrawableRes
  public val sky: Int,
)
