// this file is auto-generated, please do not edit this file。
// 该文件是自动生成的文件，请不要编辑。
//
package cn.loopon.cafe

public interface Cup {
  public val mipmap: CafeMipmap

  public val drawable: CafeDrawable

  public val color: CafeColor
}

public object MAIN : Cup {
  public override val color: CafeColor = CafeColor(
      purple_200 = com.azalea.cafe.R.color.purple_200,
      purple_500 = com.azalea.cafe.R.color.purple_500,
      purple_700 = com.azalea.cafe.R.color.purple_700,
      teal_200 = com.azalea.cafe.R.color.teal_200,
      teal_700 = com.azalea.cafe.R.color.teal_700,
      black = com.azalea.cafe.R.color.black,
      white = com.azalea.cafe.R.color.white
      )


  public override val mipmap: CafeMipmap = CafeMipmap(
      sky = com.azalea.cafe.R.mipmap.sky,
      ic_launcher = com.azalea.cafe.R.mipmap.ic_launcher,
      ic_launcher_round = com.azalea.cafe.R.mipmap.ic_launcher_round
      )


  public override val drawable: CafeDrawable = CafeDrawable(
      ic_launcher_background = com.azalea.cafe.R.drawable.ic_launcher_background,
      ic_launcher_foreground = com.azalea.cafe.R.drawable.ic_launcher_foreground,
      sky = com.azalea.cafe.R.drawable.sky
      )

}

public object DUSK : Cup {
  public override val color: CafeColor = CafeColor(
      purple_200 = com.azalea.cafe.R.color.purple_200_dusk,
      purple_500 = com.azalea.cafe.R.color.purple_500,
      purple_700 = com.azalea.cafe.R.color.purple_700,
      teal_200 = com.azalea.cafe.R.color.teal_200,
      teal_700 = com.azalea.cafe.R.color.teal_700,
      black = com.azalea.cafe.R.color.black,
      white = com.azalea.cafe.R.color.white
      )


  public override val mipmap: CafeMipmap = CafeMipmap(
      sky = com.azalea.cafe.R.mipmap.sky_dusk,
      ic_launcher = com.azalea.cafe.R.mipmap.ic_launcher,
      ic_launcher_round = com.azalea.cafe.R.mipmap.ic_launcher_round
      )


  public override val drawable: CafeDrawable = CafeDrawable(
      sky = com.azalea.cafe.R.drawable.sky_dusk,
      ic_launcher_background = com.azalea.cafe.R.drawable.ic_launcher_background,
      ic_launcher_foreground = com.azalea.cafe.R.drawable.ic_launcher_foreground
      )

}

public object NIGHT : Cup {
  public override val color: CafeColor = CafeColor(
      purple_200 = com.azalea.cafe.R.color.purple_200,
      purple_500 = com.azalea.cafe.R.color.purple_500,
      purple_700 = com.azalea.cafe.R.color.purple_700,
      teal_200 = com.azalea.cafe.R.color.teal_200,
      teal_700 = com.azalea.cafe.R.color.teal_700,
      black = com.azalea.cafe.R.color.black,
      white = com.azalea.cafe.R.color.white
      )


  public override val mipmap: CafeMipmap = CafeMipmap(
      sky = com.azalea.cafe.R.mipmap.sky_night,
      ic_launcher = com.azalea.cafe.R.mipmap.ic_launcher,
      ic_launcher_round = com.azalea.cafe.R.mipmap.ic_launcher_round
      )


  public override val drawable: CafeDrawable = CafeDrawable(
      sky = com.azalea.cafe.R.drawable.sky_night,
      ic_launcher_background = com.azalea.cafe.R.drawable.ic_launcher_background,
      ic_launcher_foreground = com.azalea.cafe.R.drawable.ic_launcher_foreground
      )

}
